In [2]:
import yfinance as yf
import pandas as pd

# Define tickers and date range
tickers = ["AAPL", "MSFT", "GOOGL", "TSLA", "SPY", "BND"]
start_date = "2015-01-01"
end_date = "2025-01-01"

# Fetch data using yfinance
print("Fetching stock data...")
try:
    stock_data = yf.download(tickers, start=start_date, end=end_date)
    
    # Print the full response structure
    print("Raw Data Columns:", stock_data.columns)

    # Check if "Adj Close" exists
    if "Adj Close" in stock_data:
        stock_data = stock_data["Adj Close"]
        print("Data fetched successfully!")
    else:
        print("Warning: 'Adj Close' column not found. Displaying full data structure instead.")
    
except Exception as e:
    print(f"Error fetching data: {e}")
    stock_data = None

# Display first few rows
if stock_data is not None:
    display(stock_data.head())  # Use display() for Jupyter Notebook
else:
    print("No stock data fetched.")

Fetching stock data...

[*********************100%***********************]  6 of 6 completed

Raw Data Columns: MultiIndex([( 'Close',  'AAPL'),
            ( 'Close',   'BND'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'MSFT'),
            ( 'Close',   'SPY'),
            ( 'Close',  'TSLA'),
            (  'High',  'AAPL'),
            (  'High',   'BND'),
            (  'High', 'GOOGL'),
            (  'High',  'MSFT'),
            (  'High',   'SPY'),
            (  'High',  'TSLA'),
            (   'Low',  'AAPL'),
            (   'Low',   'BND'),
            (   'Low', 'GOOGL'),
            (   'Low',  'MSFT'),
            (   'Low',   'SPY'),
            (   'Low',  'TSLA'),
            (  'Open',  'AAPL'),
            (  'Open',   'BND'),
            (  'Open', 'GOOGL'),
            (  'Open',  'MSFT'),
            (  'Open',   'SPY'),
            (  'Open',  'TSLA'),
            ('Volume',  'AAPL'),
            ('Volume',   'BND'),
            ('Volume', 'GOOGL'),
            ('Volume',  'MSFT'),
            ('Volume',   'SPY'),
            ('Volume',  'TSLA')],
           names=['Price', 'Ticker'])
Warning: 'Adj Close' column not found. Displaying full data structure instead.

Price           Close                                                          \
Ticker           AAPL        BND      GOOGL       MSFT         SPY       TSLA
Date
2015-01-02  24.347170  62.573143  26.381865  40.152473  172.592834  14.620667
2015-01-05  23.661282  62.754814  25.879185  39.783249  169.475937  14.006000
2015-01-06  23.663502  62.936520  25.240503  39.199329  167.879608  14.085333
2015-01-07  23.995317  62.974365  25.166271  39.697380  169.971603  14.063333
2015-01-08  24.917274  62.875969  25.253954  40.865189  172.987747  14.041333

Price            High                                   ...       Open  \
Ticker           AAPL        BND      GOOGL       MSFT  ...      GOOGL
Date                                                    ...
2015-01-02  24.817055  62.603427  26.693236  40.719211  ...  26.533812
2015-01-05  24.195749  62.777526  26.304145  40.126724  ...  26.262296
2015-01-06  23.924054  63.125791  25.966370  40.143890  ...  25.930999
2015-01-07  24.095529  63.050073  25.482126  39.894879  ...  25.455225
2015-01-08  24.975175  62.921392  25.283346  41.002579  ...  24.984929

Price                                            Volume                     \
Ticker           MSFT         SPY       TSLA       AAPL      BND     GOOGL
Date
2015-01-02  40.066605  173.390991  14.858000  212818400  2218800  26480000
2015-01-05  39.817594  171.534312  14.303333  257142000  5820100  41182000
2015-01-06  39.826175  169.786749  14.004000  263188400  3887600  54456000
2015-01-07  39.482707  169.223867  14.223333  160423600  2433400  46918000
2015-01-08  40.143887  171.399856  14.187333  237458000  1873400  73054000

Price
Ticker          MSFT        SPY      TSLA
Date
2015-01-02  27913900  121465900  71466000
2015-01-05  39673900  169632600  80527500
2015-01-06  36447900  209151400  93928500
2015-01-07  29114100  125346700  44526000
2015-01-08  29645200  147217800  51637500

[5 rows x 30 columns]